# Generated by Django 4.1.7 on 2023-03-31 07:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cpanelapp', '0003_file1'),
    ]

    operations = [
        migrations.AddField(
            model_name='file1',
            name='bname',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
