# Generated by Django 4.1.7 on 2023-04-06 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cpanelapp', '0005_category_subcategory_delete_file1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subcategory',
            old_name='name',
            new_name='category',
        ),
    ]
