# Generated by Django 4.1.7 on 2023-04-06 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cpanelapp', '0007_programming_course'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subcategory',
            old_name='bname',
            new_name='name',
        ),
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.DeleteModel(
            name='Programming',
        ),
    ]
